# Generated by Django 4.1.2 on 2023-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default=7220000000, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
